<?php

namespace App\Http\Controllers\Admin;


use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class CallController extends VoyagerBaseController
{
    public function store(Request $request)
    {
        dd($request);
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
